### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by breversa** [saschpe/BirthdayCalendar#14]
Hi !
Are you look for a french translator ? I’m willing to contribute ! :)

**Comment by saschpe** [comment]
Hi there,



On Mon, 2020-01-20 at 04:36 -0800, breversa wrote:
> Hi !
> Are you look for a french translator ? I’m willing to contribute ! :)

of course! Translations are always welcome. Depending on your
preference, you could start from the German [1] or English [0] strings.
If you can, you could simply do a Github Pull Request. Otherwise, you
could send me the file and I'll add it under your name.

[0] 
https://github.com/saschpe/BirthdayCalendar/blob/master/mobile/src/main/res/values/strings.xml
[1] 
https://github.com/saschpe/BirthdayCalendar/blob/master/mobile/src/main/res/values-de/strings.xml

-- 
Mit freundlichen Grüßen,
Sascha Peilicke

**Comment by breversa** [comment]
Okay ! I’m not very familiar with Git but I’ll give it a try !
